-- ============================================================
-- Gustos — 10 recettes de démonstration
-- Coller dans : Supabase Dashboard → SQL Editor → Run
-- Remplace 'enzo.bellenguez@gmail.com' par ton email si différent
-- ============================================================

INSERT INTO public.recipes (id, user_id, data, updated_at)
SELECT
  (r.data::jsonb->>'id')::uuid,
  u.id,
  r.data::jsonb,
  now()
FROM auth.users u
CROSS JOIN (VALUES

  ('{"id":"10000000-0000-0000-0000-000000000001","name":"Quiche Lorraine","category":"Entrées","basePeople":6,"prepTime":20,"cookTime":35,"description":"La classique lorraine : pâte croustillante, lardons fumés et royale crémeuse.","ingredients":[{"name":"Pâte brisée","qty":1,"unit":"pièce(s)"},{"name":"Lardons fumés","qty":200,"unit":"g"},{"name":"Crème fraîche épaisse","qty":20,"unit":"cl"},{"name":"Oeufs","qty":3,"unit":"pièce(s)"},{"name":"Gruyère râpé","qty":80,"unit":"g"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre noir","qty":1,"unit":"pincée"},{"name":"Noix de muscade","qty":1,"unit":"pincée"}],"steps":[{"text":"Préchauffer le four à 180°C. Étaler la pâte dans un moule, piquer le fond à la fourchette.","image":null},{"text":"Faire revenir les lardons à sec jusqu''à légère coloration. Égoutter sur du papier absorbant.","image":null},{"text":"Battre les oeufs avec la crème, saler, poivrer, ajouter la muscade.","image":null},{"text":"Répartir les lardons sur le fond, verser la royale et parsemer de gruyère.","image":null},{"text":"Cuire 30-35 min jusqu''à ce que la surface soit dorée et la garniture prise.","image":null}],"coverImage":null,"images":[],"tags":["classique","fromage","lardons"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000002","name":"Boeuf Bourguignon","category":"Viandes","basePeople":4,"prepTime":30,"cookTime":120,"description":"Un grand classique de la cuisine française mijotée au vin rouge de Bourgogne.","ingredients":[{"name":"Boeuf à braiser","qty":800,"unit":"g"},{"name":"Vin rouge de Bourgogne","qty":75,"unit":"cl"},{"name":"Lardons","qty":150,"unit":"g"},{"name":"Champignons de Paris","qty":200,"unit":"g"},{"name":"Carottes","qty":3,"unit":"pièce(s)"},{"name":"Oignons","qty":2,"unit":"pièce(s)"},{"name":"Ail","qty":3,"unit":"gousse(s)"},{"name":"Bouquet garni","qty":1,"unit":"pièce(s)"},{"name":"Farine","qty":2,"unit":"cuil. à soupe"},{"name":"Beurre","qty":30,"unit":"g"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre","qty":1,"unit":"pincée"}],"steps":[{"text":"Couper le boeuf en gros cubes. Faire revenir les lardons dans une cocotte, réserver.","image":null},{"text":"Dorer les morceaux de boeuf sur toutes les faces dans la graisse des lardons. Réserver.","image":null},{"text":"Faire revenir oignons émincés et carottes coupées en rondelles. Ajouter l''ail écrasé.","image":null},{"text":"Saupoudrer de farine, mélanger, puis verser le vin rouge. Porter à ébullition.","image":null},{"text":"Remettre le boeuf et les lardons, ajouter le bouquet garni. Couvrir et mijoter 1h30 à feu doux.","image":null},{"text":"20 min avant la fin, faire revenir les champignons au beurre et les ajouter. Rectifier l''assaisonnement.","image":null}],"coverImage":null,"images":[],"tags":["mijoté","vin rouge","hiver"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000003","name":"Ratatouille","category":"Végétarien","basePeople":4,"prepTime":25,"cookTime":45,"description":"Le plat ensoleillé de la Provence : légumes d''été confits à l''huile d''olive.","ingredients":[{"name":"Aubergines","qty":2,"unit":"pièce(s)"},{"name":"Courgettes","qty":2,"unit":"pièce(s)"},{"name":"Poivrons rouges","qty":2,"unit":"pièce(s)"},{"name":"Tomates","qty":4,"unit":"pièce(s)"},{"name":"Oignons","qty":2,"unit":"pièce(s)"},{"name":"Ail","qty":3,"unit":"gousse(s)"},{"name":"Huile d''olive","qty":6,"unit":"cuil. à soupe"},{"name":"Thym","qty":2,"unit":"botte(s)"},{"name":"Basilic frais","qty":1,"unit":"botte(s)"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre","qty":1,"unit":"pincée"}],"steps":[{"text":"Couper tous les légumes en dés de 2 cm. Saler les aubergines 15 min et éponger.","image":null},{"text":"Faire revenir les oignons et l''ail dans l''huile d''olive jusqu''à transparence.","image":null},{"text":"Ajouter les poivrons et cuire 10 min, puis les aubergines 10 min supplémentaires.","image":null},{"text":"Incorporer les courgettes et les tomates. Ajouter le thym, saler, poivrer.","image":null},{"text":"Couvrir et laisser mijoter 25 min. Rectifier l''assaisonnement, parsemer de basilic.","image":null}],"coverImage":null,"images":[],"tags":["provençal","été","vegan"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000004","name":"Tarte Tatin","category":"Desserts","basePeople":8,"prepTime":20,"cookTime":40,"description":"La tarte renversée aux pommes caramélisées, née d''un heureux accident à Lamotte-Beuvron.","ingredients":[{"name":"Pommes Golden","qty":6,"unit":"pièce(s)"},{"name":"Sucre en poudre","qty":150,"unit":"g"},{"name":"Beurre","qty":80,"unit":"g"},{"name":"Pâte feuilletée","qty":1,"unit":"pièce(s)"},{"name":"Jus de citron","qty":1,"unit":"cuil. à soupe"}],"steps":[{"text":"Éplucher et couper les pommes en quartiers. Les arroser de jus de citron.","image":null},{"text":"Dans une poêle allant au four, faire fondre le beurre puis ajouter le sucre. Cuire jusqu''au caramel blond.","image":null},{"text":"Disposer les pommes en rosace dans le caramel, côté bombé vers le bas. Cuire 10 min à feu moyen.","image":null},{"text":"Recouvrir d''un cercle de pâte feuilletée en rentrant les bords sous les pommes.","image":null},{"text":"Enfourner à 200°C pendant 25-30 min. Laisser refroidir 5 min puis retourner sur un plat.","image":null}],"coverImage":null,"images":[],"tags":["dessert","pommes","caramel","classique"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000005","name":"Soupe à l''Oignon Gratinée","category":"Soupes","basePeople":4,"prepTime":15,"cookTime":60,"description":"La vraie soupe à l''oignon parisienne : oignons fondus, croûtons et gruyère gratiné.","ingredients":[{"name":"Oignons","qty":1,"unit":"kg"},{"name":"Beurre","qty":50,"unit":"g"},{"name":"Farine","qty":1,"unit":"cuil. à soupe"},{"name":"Vin blanc sec","qty":10,"unit":"cl"},{"name":"Bouillon de boeuf","qty":1,"unit":"L"},{"name":"Baguette","qty":1,"unit":"pièce(s)"},{"name":"Gruyère râpé","qty":150,"unit":"g"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre","qty":1,"unit":"pincée"}],"steps":[{"text":"Émincer finement les oignons. Les faire fondre dans le beurre à feu doux pendant 40 min en remuant régulièrement jusqu''à caramélisation.","image":null},{"text":"Saupoudrer de farine, mélanger 2 min, puis déglacer au vin blanc.","image":null},{"text":"Verser le bouillon chaud, saler, poivrer. Laisser mijoter 15 min.","image":null},{"text":"Verser la soupe dans des bols allant au four. Poser des tranches de baguette grillée dessus.","image":null},{"text":"Couvrir généreusement de gruyère râpé. Gratiner sous le gril du four 5-7 min.","image":null}],"coverImage":null,"images":[],"tags":["hiver","réconfort","gratiné"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000006","name":"Pâtes à la Carbonara","category":"Pâtes","basePeople":2,"prepTime":10,"cookTime":15,"description":"La vraie carbonara sans crème : oeufs, guanciale et pecorino pour une sauce soyeuse.","ingredients":[{"name":"Spaghetti","qty":200,"unit":"g"},{"name":"Guanciale (ou pancetta)","qty":100,"unit":"g"},{"name":"Oeufs entiers","qty":2,"unit":"pièce(s)"},{"name":"Jaunes d''oeufs","qty":2,"unit":"pièce(s)"},{"name":"Pecorino Romano râpé","qty":80,"unit":"g"},{"name":"Poivre noir concassé","qty":1,"unit":"cuil. à café"},{"name":"Sel","qty":1,"unit":"pincée"}],"steps":[{"text":"Cuire les pâtes al dente dans une grande quantité d''eau salée. Réserver 1 verre d''eau de cuisson.","image":null},{"text":"Couper le guanciale en lardons et les faire revenir à sec jusqu''à légère croustillance. Retirer du feu.","image":null},{"text":"Battre oeufs, jaunes et pecorino. Poivrer généreusement.","image":null},{"text":"Hors du feu, mélanger les pâtes égouttées avec le guanciale. Verser la sauce aux oeufs en remuant vite.","image":null},{"text":"Ajouter l''eau de cuisson cuillère par cuillère pour obtenir une sauce crémeuse. Servir immédiatement.","image":null}],"coverImage":null,"images":[],"tags":["rapide","italien","no-crème"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000007","name":"Salade Niçoise","category":"Salades","basePeople":2,"prepTime":20,"cookTime":10,"description":"La salade de Nice : thon, oeufs durs, olives et anchois sur un lit de légumes croquants.","ingredients":[{"name":"Thon en boîte","qty":160,"unit":"g"},{"name":"Oeufs","qty":2,"unit":"pièce(s)"},{"name":"Tomates cerises","qty":200,"unit":"g"},{"name":"Haricots verts","qty":150,"unit":"g"},{"name":"Pommes de terre nouvelles","qty":200,"unit":"g"},{"name":"Olives noires","qty":50,"unit":"g"},{"name":"Anchois","qty":4,"unit":"filet(s)"},{"name":"Laitue","qty":1,"unit":"pièce(s)"},{"name":"Huile d''olive","qty":3,"unit":"cuil. à soupe"},{"name":"Vinaigre de vin","qty":1,"unit":"cuil. à soupe"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre","qty":1,"unit":"pincée"}],"steps":[{"text":"Cuire les oeufs durs 10 min. Cuire les haricots verts et les pommes de terre à l''eau salée.","image":null},{"text":"Préparer la vinaigrette : huile d''olive, vinaigre, sel, poivre.","image":null},{"text":"Dresser la laitue dans les assiettes. Disposer les tomates, haricots, pommes de terre en quartiers.","image":null},{"text":"Ajouter le thon émietté, les oeufs coupés en deux, les olives et les filets d''anchois.","image":null},{"text":"Arroser de vinaigrette au moment de servir.","image":null}],"coverImage":null,"images":[],"tags":["estival","sans cuisson","méditerranée"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000008","name":"Saumon en Papillote","category":"Poissons","basePeople":2,"prepTime":10,"cookTime":20,"description":"Saumon cuit à l''étouffée avec citron et herbes fraîches — simple, sain et parfumé.","ingredients":[{"name":"Filets de saumon","qty":2,"unit":"pièce(s)"},{"name":"Citron","qty":1,"unit":"pièce(s)"},{"name":"Aneth frais","qty":1,"unit":"botte(s)"},{"name":"Huile d''olive","qty":2,"unit":"cuil. à soupe"},{"name":"Ail","qty":2,"unit":"gousse(s)"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre","qty":1,"unit":"pincée"}],"steps":[{"text":"Préchauffer le four à 200°C. Découper deux grandes feuilles de papier sulfurisé.","image":null},{"text":"Poser un filet de saumon sur chaque feuille. Arroser d''huile d''olive.","image":null},{"text":"Ajouter l''ail émincé, les rondelles de citron, l''aneth. Saler et poivrer.","image":null},{"text":"Fermer les papillotes hermétiquement en repliant les bords plusieurs fois.","image":null},{"text":"Enfourner 18-20 min. Ouvrir les papillotes à table pour ne pas perdre les arômes.","image":null}],"coverImage":null,"images":[],"tags":["healthy","poisson","rapide"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000009","name":"Crème Brûlée","category":"Desserts","basePeople":4,"prepTime":15,"cookTime":50,"description":"La crème aux oeufs vanillée avec sa fine couche de caramel craquant — le dessert iconique.","ingredients":[{"name":"Crème liquide entière","qty":50,"unit":"cl"},{"name":"Jaunes d''oeufs","qty":5,"unit":"pièce(s)"},{"name":"Sucre en poudre","qty":100,"unit":"g"},{"name":"Gousse de vanille","qty":1,"unit":"pièce(s)"},{"name":"Cassonade","qty":4,"unit":"cuil. à soupe"}],"steps":[{"text":"Préchauffer le four à 150°C. Fendre la gousse de vanille, gratter les graines dans la crème et chauffer sans bouillir.","image":null},{"text":"Blanchir les jaunes avec le sucre. Verser la crème chaude progressivement en fouettant.","image":null},{"text":"Filtrer la préparation et la répartir dans 4 ramequins.","image":null},{"text":"Cuire au bain-marie au four pendant 45-50 min. La crème doit être prise mais encore légèrement tremblante.","image":null},{"text":"Réfrigérer au moins 2h. Avant de servir, saupoudrer de cassonade et caraméliser au chalumeau.","image":null}],"coverImage":null,"images":[],"tags":["dessert","vanille","caramel","classique"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text),

  ('{"id":"10000000-0000-0000-0000-000000000010","name":"Poulet Rôti aux Herbes","category":"Viandes","basePeople":4,"prepTime":15,"cookTime":80,"description":"Le dimanche traditionnel : un poulet entier rôti avec ail, citron et herbes de Provence.","ingredients":[{"name":"Poulet entier","qty":1,"unit":"pièce(s)"},{"name":"Beurre","qty":50,"unit":"g"},{"name":"Ail","qty":4,"unit":"gousse(s)"},{"name":"Citron","qty":1,"unit":"pièce(s)"},{"name":"Herbes de Provence","qty":2,"unit":"cuil. à café"},{"name":"Romarin","qty":2,"unit":"botte(s)"},{"name":"Huile d''olive","qty":2,"unit":"cuil. à soupe"},{"name":"Sel","qty":1,"unit":"pincée"},{"name":"Poivre","qty":1,"unit":"pincée"}],"steps":[{"text":"Sortir le poulet 30 min à température ambiante. Préchauffer le four à 200°C.","image":null},{"text":"Mélanger beurre ramolli, herbes de Provence, sel et poivre. Glisser ce beurre sous la peau du poulet.","image":null},{"text":"Farcir la cavité avec le citron coupé en deux, l''ail en chemise et le romarin.","image":null},{"text":"Arroser le poulet d''huile d''olive, saler et poivrer l''extérieur. Brider si nécessaire.","image":null},{"text":"Rôtir 1h15-1h20 en arrosant toutes les 20 min avec le jus de cuisson. Laisser reposer 10 min avant de découper.","image":null}],"coverImage":null,"images":[],"tags":["dimanche","tradition","famille"],"createdAt":"2026-01-01T12:00:00.000Z","updatedAt":"2026-01-01T12:00:00.000Z"}'::text)

) AS r(data)
WHERE u.email = 'enzo.bellenguez@gmail.com'
ON CONFLICT (id) DO NOTHING;
